after_success: |
  if ! [ -z "$TRAVIS_TAG" ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      (cd sbt-cross && exec sbt publishSigned sonatypeReleaseAll)
  elif [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$TRAVIS_BRANCH" == master ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      (cd sbt-cross && exec sbt publishSigned)
  fi
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  api_key: $GITHUB_AUTH
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk7
language: scala
script:
  - '[ -z "$TRAVIS_TAG" ] || export SBT_OPTS=-Drelease=true'
  - (cd sbt-cross && exec sbt 'all checkFormat package test')
